name: Build and deploy code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling get repo
        uses: actions/checkout@4
      - name: say hi to ld
        run: echo "hello ld"

